FROM teamide/ubuntu-node:1.1


RUN apt-get update && \
    apt-get install -y language-pack-zh-hans && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    echo 'LANG="zh_CN.UTF-8"'>>/etc/environment && \
    echo 'LC_ALL="zh_CN.UTF-8"'>>/etc/environment
