FROM ubuntu:22.04

# 使用 国内 源
RUN cp sources.list /etc/apt/sources.list

RUN apt-get update && \
    apt-get install -y ca-certificates nodejs npm git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /data
